# Absences

. = presente  
! = late  
x = absent  
- = not enrolled

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
library(dplyr); library(knitr); library(kableExtra)
tribble(
~'Name',                      ~'Week 1', ~'Week 2', ~'Week 3', ~'Week 4', ~'Week 5', ~'Week 6',
 "Bennett, Ana",                    '.',       '.',       '.',       '.',       '.',       '.', 
 "Goldin, Anne",                    '.',       '.',       '.',       '.',       '.',       '.', 
 "Hur, Kyung Won",                  '.',       '.',       '.',       '.',       '.',       '.', 
 "Koser, Nathan",                   '.',       '.',       '.',       '.',       '.',       '.', 
 "Lopez Otero, Julio Cesar",        '.',       '.',       '.',       '.',       '.',       '.', 
 "Mamadou Yacoubou, Tadjou-N'Dine", '.',       '.',       '.',       '.',       '.',       '.', 
 "Oakden, Christopher",             '.',       '.',       '.',       '.',       '.',       '.', 
 "Orejarena, Francisco",            '.',       '.',       '.',       '.',       '.',       '.') %>%
  as.data.frame(.) %>% 
  kable(.) %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```


```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
tribble(
~'Name',                      ~'Week 7', ~'Week 8', ~'Week 9', ~'Week 10', ~'Week 11', ~'Week 12',
 "Bennett, Ana",                    '.',       '.',       '.',        '.',        '.',        '.', 
 "Goldin, Anne",                    '.',       '.',       '.',        '.',        '.',        '.', 
 "Hur, Kyung Won",                  '.',       '.',       '.',        '.',        '.',        '.', 
 "Koser, Nathan",                   '.',       '.',       '.',        '.',        '.',        '.', 
 "Lopez Otero, Julio Cesar",        '.',       '.',       '.',        '.',        '.',        '.', 
 "Mamadou Yacoubou, Tadjou-N'Dine", '.',       '.',       '.',        '.',        '.',        '.', 
 "Oakden, Christopher",             '.',       '.',       '.',        '.',        '.',        '.', 
 "Orejarena, Francisco",            '.',       '.',       '.',        '.',        '.',        '.') %>%
  as.data.frame(.) %>% 
  kable(.) %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
tribble(
~'Name',                     ~'Week 13', ~'Week 14', ~'Week 15', ~'Week 16', 
 "Bennett, Ana",                    '.',        '.',        '.',        '.', 
 "Goldin, Anne",                    '.',        '.',        '.',        '.', 
 "Hur, Kyung Won",                  '.',        '.',        '.',        '.', 
 "Koser, Nathan",                   '.',        '.',        '.',        '.', 
 "Lopez Otero, Julio Cesar",        '.',        '.',        '.',        '.', 
 "Mamadou Yacoubou, Tadjou-N'Dine", '.',        '.',        '.',        '.', 
 "Oakden, Christopher",             '.',        '.',        '.',        '.', 
 "Orejarena, Francisco",            '.',        '.',        '.',        '.') %>%
  as.data.frame(.) %>% 
  kable(.) %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```